version: '3.3'

services:
  web:
    build: .
    command: gunicorn app:app --config gunicorn.config.py
    expose:
      - 5000
  nginx:
    build: ./nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
#      - static_volume:/home/app/web/project/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
