version: 'beta'

services:
  web:
    build:
      dockerfile: Dockerfile
    command: gunicorn app:app --config gunicorn.config.py
    expose:
      - 5000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/project/static
    ports:
      - 1337:80
    depends_on:
      - web